version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: ./mvnw clean install

jobs:

  jdk11:
    docker:
      - image: cimg/openjdk:11.0.20
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

  jdk17:
    docker:
      - image: cimg/openjdk:17.0.8
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

workflows:
  build_and_test:
    jobs:
      - jdk11
      - jdk17
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare
